project_id = "ffnpobdcqcagjmlddvga"

[functions.import-districts]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.import-schools]
verify_jwt = false

[functions.import-schools-csv]
verify_jwt = false

[functions.import-schools-batch]
verify_jwt = false

[functions.clear-schools]
verify_jwt = false

[functions.import-sanction-data]
verify_jwt = false

[functions.extract-logo-colors]
verify_jwt = false

[functions.ai-role-assistant]
verify_jwt = false
