project_id = "ffnpobdcqcagjmlddvga"

[functions.import-districts]
verify_jwt = false

[functions.chat]
verify_jwt = true

[functions.import-schools]
verify_jwt = false

[functions.import-schools-csv]
verify_jwt = false

[functions.import-schools-batch]
verify_jwt = false

[functions.clear-schools]
verify_jwt = true

[functions.import-sanction-data]
verify_jwt = false

[functions.extract-logo-colors]
verify_jwt = false

[functions.ai-role-assistant]
verify_jwt = true

[functions.extract-schedule]
verify_jwt = true

[functions.extract-registration-data]
verify_jwt = true

[functions.impersonate]
verify_jwt = true

[functions.signed-url]
verify_jwt = true

[functions.upload-document]
verify_jwt = true

[functions.upload-photo]
verify_jwt = true
