project_id = "ffnpobdcqcagjmlddvga"

[functions.import-districts]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.import-schools]
verify_jwt = false

[functions.import-schools-csv]
verify_jwt = false
